# Generated by Django 5.2.9 on 2026-01-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_mobile_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uprofile',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnSSxXHLqu5lsHYkFlZkvXuo2ZamNvdqLiCg&s', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='customer', max_length=26),
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccategory', models.CharField(choices=[('residence', 'residence'), ('corporate', 'corporate')], max_length=30)),
                ('ptitle', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('summary', models.TextField()),
                ('pimage', models.ImageField(upload_to='interior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
