# Generated by Django 5.2.9 on 2026-01-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_uprofile_user_usertype_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='Dreamer', max_length=26),
        ),
    ]
