# Generated by Django 5.2.9 on 2026-02-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uprofile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcategory', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial')], max_length=30)),
                ('dname', models.CharField(max_length=30)),
                ('dstartprice', models.IntegerField()),
                ('dsummary', models.TextField()),
                ('dimage', models.ImageField(upload_to='interior')),
                ('dimage2', models.ImageField(blank=True, null=True, upload_to='interior')),
                ('dimage3', models.ImageField(blank=True, null=True, upload_to='interior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='vendor',
        ),
    ]
