# Generated by Django 5.2.9 on 2026-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_uprofile_designer_delete_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(max_length=26),
        ),
    ]
