# Generated by Django 5.2.9 on 2026-02-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': 'Interior Project', 'verbose_name_plural': 'Interior Projects'},
        ),
        migrations.AlterUniqueTogether(
            name='designer',
            unique_together={('user', 'dname')},
        ),
    ]
