# Generated by Django 5.2.9 on 2026-02-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_designer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
