# Generated by Django 5.2.9 on 2026-02-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_designer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='slug',
        ),
        migrations.CreateModel(
            name='Moodboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.designer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'unique_together': {('user', 'design')},
            },
        ),
    ]
