# Generated by Django 5.2.9 on 2026-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_designer_slug_moodboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
