# Generated by Django 5.2.9 on 2026-02-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='landmark',
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
            preserve_default=False,
        ),
    ]
