# Generated by Django 5.2.9 on 2026-02-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_site_landmark_site_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.CharField(default='DUMMY_ORDER', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.site'),
        ),
    ]
